on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master


name: Linux installation
permissions:
    contents: read
jobs:
    test-ubuntu:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11"]

        steps:
            - uses: actions/checkout@v5
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install package
              run: pip install .
            - name: Test import
              run: python -c "import gishndev; print('gishndev import successful')"
